package dev.darkokoa.datetimewheelpicker.strings

internal data class Strings(
  val monthJanuaryFull: String = "January",
  val monthFebruaryFull: String = "February",
  val monthMarchFull: String = "March",
  val monthAprilFull: String = "April",
  val monthMayFull: String = "May",
  val monthJuneFull: String = "June",
  val monthJulyFull: String = "July",
  val monthAugustFull: String = "August",
  val monthSeptemberFull: String = "September",
  val monthOctoberFull: String = "October",
  val monthNovemberFull: String = "November",
  val monthDecemberFull: String = "December",

  val monthJanuaryShort: String = "Jan",
  val monthFebruaryShort: String = "Feb",
  val monthMarchShort: String = "Mar",
  val monthAprilShort: String = "Apr",
  val monthMayShort: String = "May",
  val monthJuneShort: String = "Jun",
  val monthJulyShort: String = "Jul",
  val monthAugustShort: String = "Aug",
  val monthSeptemberShort: String = "Sep",
  val monthOctoberShort: String = "Oct",
  val monthNovemberShort: String = "Nov",
  val monthDecemberShort: String = "Dec",

  // Jalali (Persian/Solar Hijri) month names — used when CalendarType.Jalali is selected.
  // Months 1–12: فروردین … اسفند. Defaults are English transliterations so non-Persian locales
  // still produce a valid (if less idiomatic) string.
  val jalaliMonth1Full: String = "Farvardin",
  val jalaliMonth2Full: String = "Ordibehesht",
  val jalaliMonth3Full: String = "Khordad",
  val jalaliMonth4Full: String = "Tir",
  val jalaliMonth5Full: String = "Mordad",
  val jalaliMonth6Full: String = "Shahrivar",
  val jalaliMonth7Full: String = "Mehr",
  val jalaliMonth8Full: String = "Aban",
  val jalaliMonth9Full: String = "Azar",
  val jalaliMonth10Full: String = "Dey",
  val jalaliMonth11Full: String = "Bahman",
  val jalaliMonth12Full: String = "Esfand",

  val jalaliMonth1Short: String = "Far",
  val jalaliMonth2Short: String = "Ord",
  val jalaliMonth3Short: String = "Kho",
  val jalaliMonth4Short: String = "Tir",
  val jalaliMonth5Short: String = "Mor",
  val jalaliMonth6Short: String = "Sha",
  val jalaliMonth7Short: String = "Meh",
  val jalaliMonth8Short: String = "Aba",
  val jalaliMonth9Short: String = "Aza",
  val jalaliMonth10Short: String = "Dey",
  val jalaliMonth11Short: String = "Beh",
  val jalaliMonth12Short: String = "Esf",

  val timeAM: String = "AM",
  val timePM: String = "PM",

  val yearSuffix: String = "",
  val monthSuffix: String = "",
  val daySuffix: String = "",

  val digit0: Char = '0',
  val digit1: Char = '1',
  val digit2: Char = '2',
  val digit3: Char = '3',
  val digit4: Char = '4',
  val digit5: Char = '5',
  val digit6: Char = '6',
  val digit7: Char = '7',
  val digit8: Char = '8',
  val digit9: Char = '9'
)
